import Head from "next/head";
import {useCallback, useState} from "react";
import {useRecoilState} from "recoil";
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import PageLayout from "../../components/Layout/PageLayout";
import ExcelDownload from "../../components/Templates/Members/ExcelDownload";
import {stateSetting} from "../../stores/stateSetting";

const categories = [
  {
    id: 0,
    name: "명단 다운로드",
    component: <ExcelDownload />,
  },
];

const MembersPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.developSelectedCategoryId,
  );

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        developSelectedCategoryId: id,
      });
    },
    [setting, setSetting],
  );

  return (
    <FullScreenLayout>
      <Head>
        <title>명단관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <TabsWithHeader
          title={"명단관리"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default MembersPage;
