import type { NextPage } from "next";
import Head from "next/head";
// components
import Layout from "../../components/Layout/Layout";
import MemberSearch from "../../components/Templates/Members/MemberSearch";
import MembersMain from "../../components/Templates/Members/MembersMain";

const Members: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>청년현황 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 gap-y-3 xl:grid-cols-3 xl:gap-x-4 xl:h-screen">
        <div className="bg-white xl:col-span-1">
          <MemberSearch />
        </div>
        <div className="h-full xl:col-span-2">
          <MembersMain />
        </div>
      </div>
    </Layout>
  );
};

export default Members;
