import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import graphlqlRequestClient from "../../../client/graphqlRequestClient";
import Button from "../../../components/Atoms/Button/Button";
import EmptyStateSimple from "../../../components/Atoms/EmptyStates/EmptyStateSimple";
import EmptyStateStarting from "../../../components/Atoms/EmptyStates/EmptyStateStarting";
import Footer from "../../../components/Atoms/Footer";
import SectionHeader from "../../../components/Atoms/SectionHeader";
import Spinner from "../../../components/Atoms/Spinner";
import TabsWithHeader from "../../../components/Atoms/Tabs/TabsWithHeader";
import UserInfomation from "../../../components/Blocks/Infomation/UserInfomation";
import Layout from "../../../components/Layout/Layout";
import {
  SearchUsersQuery,
  SearchUsersQueryVariables,
  useSearchUsersQuery,
} from "../../../graphql/generated";
import FullWidthButton from "../../../components/Atoms/Button/FullWidthButton";

interface NewFamilyMemberProps {}

const NewFamilyMember = ({}: NewFamilyMemberProps) => {
  const router = useRouter();
  const { isLoading, data } = useSearchUsersQuery<
    SearchUsersQuery,
    SearchUsersQueryVariables
  >(
    graphlqlRequestClient,
    {
      name: typeof router.query.slug === "string" ? router.query.slug : null,
    },
    {
      staleTime: 3 * 60 * 1000,
    }
  );

  return (
    <Layout>
      <Head>
        <title>새가족 - {router.query.slug} | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.query.slug !== undefined && (
        <SectionHeader title={router.query.slug} subtitle={"새가족셀"} goBack />
      )}
      <div className="px-2 pt-2">
        <div className="bg-white rounded-md py-5 px-4">
          {isLoading ? (
            <Spinner />
          ) : data ? (
            <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="md:col-span-2">
                <UserInfomation
                  name={data.findUsers.nodes[0].name}
                  gender={data.findUsers.nodes[0].gender}
                  isActive={data.findUsers.nodes[0].isActive}
                  birthday={data.findUsers.nodes[0].birthday}
                  phone={data.findUsers.nodes[0].phone}
                  address={data.findUsers.nodes[0].address}
                  description={data.findUsers.nodes[0].description}
                />
              </div>
              <div className="md:col-span-1">
                <h6 className="pb-5 text-lg">블레싱/새싹 편성</h6>
                <div className="flex-1">
                  <FullWidthButton
                    disabled={false}
                    onClickHandler={() => {
                      console.log("블레싱");
                    }}
                    text={"블레싱 편성"}
                  />
                </div>
                <div className="flex-1 mt-4">
                  <FullWidthButton
                    disabled={false}
                    bgColor={"bg-GRAY004"}
                    onClickHandler={() => {
                      console.log("새싹");
                    }}
                    text={"새싹 편성"}
                  />
                </div>
              </div>
            </section>
          ) : (
            <EmptyStateSimple />
          )}
        </div>
      </div>
      <Footer />
    </Layout>
  );
};

export default NewFamilyMember;
