import Head from "next/head";
import {useCallback, useState} from "react";
import {useRecoilState} from "recoil";
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import Layout from "../../components/Layout/Layout";
import PageLayout from "../../components/Layout/PageLayout";
import BarnabasCMS from "../../components/Templates/DevelopCMS/BarnabasCMS";
import CellMeetingCMS from "../../components/Templates/DevelopCMS/CellMeetingCMS";
import NewFamilyCMS from "../../components/Templates/DevelopCMS/NewFamilyCMS";
import ServiceCMS from "../../components/Templates/DevelopCMS/ServiceCMS";
import {stateSetting} from "../../stores/stateSetting";

const categories = [
  {
    id: 0,
    name: "예배데이터",
    component: <ServiceCMS />,
  },
  {
    id: 1,
    name: "셀모임데이터",
    component: <CellMeetingCMS />,
  },
  {
    id: 2,
    name: "새가족데이터",
    component: <NewFamilyCMS />,
  },
  {
    id: 3,
    name: "바나바데이터",
    component: <BarnabasCMS />,
  },
];

const DevelopCMS = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.developSelectedCategoryId
  );

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        developSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  return (
    <Layout>
      <Head>
        <title>개발자 CMS | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"CMS"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default DevelopCMS;
