import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Register: NextPage = () => {
  return (
    <section>
      <Head>
        <title>새가족등록 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article>
        <header className='flex'>
          <h4 className='text-2xl font-bold tracking-wide'>새가족 등록</h4>
        </header>
        
        <div className=''>

        </div>
      </article>
    </section>
  )
}

export default Register
