import Head from "next/head";
import {useCallback, useState} from "react";
import {useRecoilState} from "recoil";
import {stateSetting} from "../../stores/stateSetting";
//components
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import PageLayout from "../../components/Layout/PageLayout";
import DiscipleClass from "../../components/Templates/Disciple/DiscipleClass";
import DiscipleClassApplication from "../../components/Templates/Disciple/DiscipleClassApplication";

const categories = [
  {
    id: 0,
    name: "제자반 지원자 관리",
    component: <DiscipleClassApplication />,
  },
  {
    id: 1,
    name: "역대 제자반 기수",
    component: <DiscipleClass />,
  },
];

const DisciplePage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.discipleSelectedCategoryId,
  );

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        discipleSelectedCategoryId: id,
      });
    },
    [setting, setSetting],
  );

  return (
    <FullScreenLayout>
      <Head>
        <title>제자반 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"제자반"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default DisciplePage;
