import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useLayoutEffect, useState } from "react";
import Layout from "../../components/Layout/Layout";
import NewFamilyRegister from "../../components/Templates/NewFamily/NewFamilyRegister";
import NewFamilyManagement from "../../components/Templates/NewFamily/NewFamilyManagement";
import { useRecoilState, useSetRecoilState } from "recoil";
import { selectedState } from "../../stores/selectedState";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import Footer from "../../components/Atoms/Footer";
import { stateSetting } from "../../stores/stateSetting";

const categories = [
  { id: 0, name: "새가족 등록카드", component: <NewFamilyRegister /> },
  {
    id: 1,
    name: "새가족 명단관리",
    component: <NewFamilyManagement />,
  },
];

const Register: NextPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.newFamilySelectedCategoryId
  );
  const setSelectedCell = useSetRecoilState(selectedState);
  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        newFamilySelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  console.log(setting);

  useLayoutEffect(() => {
    setSelectedCell({
      selectedCell: {
        cellId: "39",
        cellName: "새가족셀",
      },
      selectedMember: {
        memeberId: "",
        memberName: "",
      },
    });
  }, []);

  return (
    <Layout>
      <Head>
        <title>새가족관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TabsWithHeader
        title={"새가족부"}
        tabs={categories}
        currentTab={categoryId}
        setCurrentTab={setCategoryId}
        setSettingHandler={setSettingHandler}
      />

      <div className="px-2 pt-2">{categories[categoryId].component}</div>
      <Footer />
    </Layout>
  );
};

export default Register;
