import {NextPage} from "next";
import Head from "next/head";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
// components
import EmptyStateSimple from "../../../../components/Atoms/EmptyStates/EmptyStateSimple";
import MemberHeader from "../../../../components/Blocks/Headers/MemberHeader";
import EditUserInfomation from "../../../../components/Blocks/Infomation/EditUserInfomation";
import UserInfomation from "../../../../components/Blocks/Infomation/UserInfomation";
import Layout from "../../../../components/Layout/Layout";
// api
import graphlqlRequestClient from "../../../../client/graphqlRequestClient";
import BlockContainer from "../../../../components/Atoms/Container/BlockContainer";
import Container from "../../../../components/Atoms/Container/Container";
import SectionBackground from "../../../../components/Atoms/Container/SectionBackground";
import SectionContainer from "../../../../components/Atoms/Container/SectionContainer";
import Footer from "../../../../components/Atoms/Footer";
import SkeletonMemberInfo from "../../../../components/Atoms/Skeleton/SkeletonMemberInfo";
import {
  FindUserQuery,
  FindUserQueryVariables,
  useFindUserQuery,
} from "../../../../graphql/generated";
import UserCellmeetingHistory from "./_components/UserCellmeetingHistory/UserCellmeetingHistory";

interface MemberDetailPage {}

const MemberDetailPage: NextPage<MemberDetailPage> = () => {
  const router = useRouter();
  const [userId, setUserId] = useState<string>("");
  const [editMode, setEditMode] = useState(false);

  const {isLoading, isFetching, data} = useFindUserQuery<
    FindUserQuery,
    FindUserQueryVariables
  >(
    graphlqlRequestClient,
    {
      id: userId,
    },
    {
      enabled: userId !== "",
      staleTime: 10 * 60 * 1000,
      cacheTime: 15 * 60 * 1000,
    }
  );

  useEffect(() => {
    if (router.isReady) {
      if (typeof router.query.userId === "string") {
        setUserId(router.query.userId);
      } else {
        setUserId("");
      }
    }
  }, [router]);

  return (
    <Layout>
      <Head>
        <title>청년정보 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <SectionBackground>
          {isLoading || isFetching ? (
            <SkeletonMemberInfo />
          ) : (
            <SectionContainer>
              {data ? (
                <div>
                  <MemberHeader
                    cellId={data.user.cell?.id}
                    cellName={data.user.cell?.name}
                    userName={data.user.name}
                    editMode={editMode}
                    setEditMode={setEditMode}
                  />
                  <BlockContainer>
                    {!editMode ? (
                      <section className="grid grid-cols-1 md:grid-cols-6 gap-6 py-3 rounded-md bg-white lg:px-4 lg:py-5">
                        <div className="md:col-span-2">
                          <UserInfomation
                            name={data.user.name}
                            gender={data.user.gender}
                            grade={data.user.grade}
                            isActive={data.user.isActive}
                            birthday={data.user.birthday}
                            phone={data.user.phone}
                            address={data.user.address}
                            registrationDate={data.user.registrationDate}
                            description={data.user.description}
                            editModeHandler={() => setEditMode(true)}
                            hasHeader={false}
                          />
                        </div>
                        <div className="md:col-span-4">
                          <UserCellmeetingHistory userId={userId} />
                        </div>
                      </section>
                    ) : (
                      <section className="rounded-md bg-white lg:px-4 lg:py-5">
                        <EditUserInfomation
                          id={data.user.id}
                          name={data.user.name}
                          gender={data.user.gender}
                          grade={data.user.grade}
                          isActive={data.user.isActive}
                          birthday={data.user.birthday}
                          phone={data.user.phone}
                          address={data.user.address}
                          description={data.user.description}
                          cell={data.user.cell}
                          registrationYear={
                            data.user.registrationDate?.split("-")[0]
                          }
                          registrationMonth={
                            data.user.registrationDate?.split("-")[1]
                          }
                          registrationDay={
                            data.user.registrationDate?.split("-")[2]
                          }
                          editModeHandler={setEditMode}
                        />
                      </section>
                    )}
                  </BlockContainer>
                </div>
              ) : (
                <div className="w-full h-screen flex justify-center items-center">
                  <EmptyStateSimple warning />
                </div>
              )}
            </SectionContainer>
          )}
        </SectionBackground>
        <Footer />
      </Container>
    </Layout>
  );
};

export default MemberDetailPage;
