import React, { useRef } from "react";
import Layout from "../../../../components/Layout/Layout";
import Head from "next/head";
import PageLayout from "../../../../components/Layout/PageLayout";
import SectionContainer from "../../../../components/Atoms/Container/SectionContainer";
import BlockContainer from "../../../../components/Atoms/Container/BlockContainer";
import ReactToPrint from "react-to-print";
import CellReportTemplate from "../../../../components/Templates/Reports/CellReportTemplate/CellReportTemplate";
import { mockCellRport } from "../../../../constants/mockCellReport";

interface CellReportPrintScreenProps {}

const CellReportPrintScreen = ({}: CellReportPrintScreenProps) => {
  const componentRef = useRef<HTMLDivElement | null>(null);

  return (
    <Layout>
      <Head>
        <title>남정훈셀 셀보고서 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <SectionContainer>
          <BlockContainer>
            <header className="relative">
              <div className="mx-auto max-w-7xl border-b border-gray-900/10 px-4 py-10 sm:px-6 lg:px-4">
                <div className="mx-auto flex max-w-2xl items-center justify-between gap-x-8 lg:mx-0 lg:max-w-none">
                  <div className="flex items-center gap-x-6">
                    <h1>
                      <div className="text-sm leading-6 text-gray-500">
                        <span className="text-gray-700">2023. 05. 07.</span>
                      </div>
                      <div className="mt-1 text-base font-semibold leading-6 text-gray-900">
                        남정훈셀
                      </div>
                    </h1>
                  </div>
                  <div className="flex items-center gap-x-4 sm:gap-x-6">
                    <ReactToPrint
                      trigger={() => (
                        <button className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                          Print
                        </button>
                      )}
                      content={() => componentRef.current}
                    />
                  </div>
                </div>
              </div>
            </header>
            <CellReportTemplate ref={componentRef} report={mockCellRport} />
          </BlockContainer>
        </SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default CellReportPrintScreen;
