import type {NextPage} from "next";
import Head from "next/head";
import {useCallback, useState} from "react";
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import PageLayout from "../../components/Layout/PageLayout";
// Tab Components
import DallantMain from "../../components/Templates/Dallant/DallantMain";
import DallantPayment from "../../components/Templates/Dallant/DallantPayment";
import DallantSetting from "../../components/Templates/Dallant/DallantSetting";
// State
import {useRecoilState} from "recoil";
import {stateSetting} from "../../stores/stateSetting";
// Data
import {useQuery} from "react-query";
import BlockContainer from "../../components/Atoms/Container/BlockContainer";
import Spinner from "../../components/Atoms/Spinner";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import CreateSeason from "../../components/Organisms/Dallant/Settings/CreateSeason";
import SeasonOffSection from "../../components/Organisms/Dallant/Settings/SeasonOffSection";
import CellDay from "../../components/Templates/Dallant/CellDay";
import CellDayOrder from "../../components/Templates/Dallant/CellDayOrder";
import {getDallentSetting} from "../../firebase/Dallant/Dallant";

const TalentPage: NextPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.talentSelectedCategoryId
  );
  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        talentSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  const {isLoading: isSettingLoading, data: initialSetting} = useQuery(
    "getTalentSetting",
    getDallentSetting
  );

  const categories = [
    {
      id: 0,
      name: "달란트 현황",
      component: <DallantMain />,
    },
    {
      id: 1,
      name: "달란트 지급",
      component: <DallantPayment />,
    },
    {
      id: 2,
      name: "셀모임의 날",
      component: <CellDay />,
    },
    {
      id: 3,
      name: "셀모임의 날 - 주문현황",
      component: <CellDayOrder />,
    },
    {
      id: 4,
      name: "달란트 세팅",
      component: (
        <DallantSetting
          initialSetting={initialSetting}
          isSettingLoading={isSettingLoading}
        />
      ),
    },
  ];

  return (
    <FullScreenLayout>
      <Head>
        <title>달란트 관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"달란트 관리"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>
          {initialSetting && initialSetting.isActivity ? (
            <>
              {isSettingLoading ? (
                <BlockContainer firstBlock>
                  <Spinner />
                </BlockContainer>
              ) : (
                <>{categories[categoryId].component}</>
              )}
            </>
          ) : (
            <BlockContainer firstBlock>
              <SeasonOffSection />
              <CreateSeason />
            </BlockContainer>
          )}
        </SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default TalentPage;
