import { useCallback, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/Layout/Layout";
import PageLayout from "../../components/Layout/PageLayout";
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
// Tab Components
import DallantMain from "../../components/Templates/Dallant/DallantMain";
import DallantPayment from "../../components/Templates/Dallant/DallantPayment";
import DallantSetting from "../../components/Templates/Dallant/DallantSetting";
// State
import { useRecoilState } from "recoil";
import { stateSetting } from "../../stores/stateSetting";
// Data
import { useQuery } from "react-query";
import { getDallentSetting } from "../../firebase/Dallant/Dallant";


const TalentPage: NextPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.talentSelectedCategoryId
  );
  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        talentSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  const { isLoading: isSettingLoading, data: initialSetting } = useQuery("getTalentSetting", getDallentSetting);

  const categories = [
    {
      id: 0,
      name: "달란트 현황",
      component: <DallantMain initialSetting={initialSetting} isSettingLoading={isSettingLoading} />,
    },
    {
      id: 1,
      name: "달란트 지급",
      component: <DallantPayment initialSetting={initialSetting} isSettingLoading={isSettingLoading} />,
    },
    {
      id: 2,
      name: "달란트 세팅",
      component: <DallantSetting initialSetting={initialSetting} isSettingLoading={isSettingLoading} />,
    },
  ];

  return (
    <Layout>
      <Head>
        <title>달란트 관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"달란트 관리"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default TalentPage;
