import React, { useCallback, useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import CellInfomationScreen from "../../../components/Templates/Cells/CellInfomationScreen";
import CellTransferScreen from "../../../components/Templates/Cells/CellTransferScreen";
import CellReportScreen from "../../../components/Templates/Cells/CellReportScreen";
import graphlqlRequestClient from "../../../client/graphqlRequestClient";
import {
  FindCellQuery,
  FindCellQueryVariables,
  useFindCellQuery,
} from "../../../graphql/generated";
import { useRecoilState } from "recoil";
import { selectedState } from "../../../stores/selectedState";
import Layout from "../../../components/Layout/Layout";
import Footer from "../../../components/Atoms/Footer";
import TabsWithHeader from "../../../components/Atoms/Tabs/TabsWithHeader";
import { stateSetting } from "../../../stores/stateSetting";

const CellDetail = () => {
  const { query } = useRouter();
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.cellSelectedCategoryId
  );
  const [selectedStatus, setSelectedStatus] = useRecoilState(selectedState);
  const { isLoading, data } = useFindCellQuery<
    FindCellQuery,
    FindCellQueryVariables
  >(
    graphlqlRequestClient,
    {
      id: Number(query.id),
    },
    {
      enabled: Boolean(query.id),
      staleTime: 5 * 60 * 1000,
      cacheTime: 10 * 60 * 1000,
    }
  );

  const categories = [
    {
      id: 0,
      name: "셀 정보",
      component: <CellInfomationScreen isLoading={isLoading} data={data} />,
    },
    {
      id: 1,
      name: "셀 보고서",
      component: <CellReportScreen />,
    },
    {
      id: 2,
      name: "셀 편성",
      component: <CellTransferScreen />,
    },
  ];

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        cellSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  useEffect(() => {
    if (data) {
      setSelectedStatus({
        ...selectedStatus,
        selectedCell: {
          cellId: data.findCell.id,
          cellName: data.findCell.name,
        },
      });
    }
  }, [data]);

  return (
    <Layout>
      <Head>
        <title>{query.cellName || data?.findCell.name} | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TabsWithHeader
        title={data?.findCell.name || "셀"}
        subtitle={"공동체"}
        tabs={categories}
        currentTab={categoryId}
        setCurrentTab={setCategoryId}
        setSettingHandler={setSettingHandler}
      />
      <div className="px-2 pt-2">{categories[categoryId].component}</div>
      <Footer />
    </Layout>
  );
};

export default CellDetail;
