import React from 'react';
import Head from 'next/head';
import Layout from '../../../../../../components/Layout/Layout';
import PageLayout from '../../../../../../components/Layout/PageLayout';
import SectionContainer from '../../../../../../components/Atoms/Container/SectionContainer';
import DallantHistoryDetail from '../../../../../../components/Templates/Dallant/DallantHistoryDetail/DallantHistoryDetail';


interface DallantHistoryProps {}

const DallantHistory = ({}: DallantHistoryProps) => {
  return (
    <Layout>
      <Head>
        <title>달란트 관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <SectionContainer>
          <DallantHistoryDetail />
        </SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default DallantHistory;
