import type {NextPage} from "next";
import Head from "next/head";
import {useCallback, useState} from "react";
//stats
import {useRecoilState} from "recoil";
import {stateSetting} from "../../stores/stateSetting";
// components
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithTwoBlock from "../../components/Atoms/Tabs/TabsWithTwoBlock";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import PageLayout from "../../components/Layout/PageLayout";
import AttendanceReportScreen from "../../components/Templates/Reports/AttendanceReportScreen";
import CellEvaluationFormScreen from "../../components/Templates/Reports/CellEvaluationFormScreen";
import CellReportSubmitScreen from "../../components/Templates/Reports/CellReportSubmitScreen";

const categories = [
  {id: 0, name: "출석체크", component: <AttendanceReportScreen />},
  {
    id: 1,
    name: "셀보고서",
    component: <CellReportSubmitScreen />,
  },
  {
    id: 2,
    name: "셀평가서",
    component: <CellEvaluationFormScreen />,
  },
];

const Training: NextPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.reportSelectedCategoryId
  );
  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        reportSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  return (
    <FullScreenLayout>
      <Head>
        <title>출석체크 및 셀보고서 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithTwoBlock
          title={"출석체크 및 셀보고서"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default Training;
