import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../../components/Layout/Layout'

const Setting: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>설정 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>설정페이지</h1>
      </div>
    </Layout>
  )
}

export default Setting
