export enum DALLANTS_COLLCTION {
  DALLENTS = "Dallents",
  ACCOUNTS = "Accounts",
  CELLS = "Cells",
  OTHERS = "Others",
  HISTORY = "History",
  MEMBERS = "Members",
  STATISTIC = "Statistic",
  OVERALL = "Overall",
  CELLSTATISTIC = "CellStatistic",
  SETTINGS = "Settings",
  RESTAURANTS = "Restaurants",
  MENUS = "Menus",
  ORDER = "Order",
  ORDERSTOCK = "OrderStock",
}

export enum CELLMEETING_COLLCTION {
  CELLMEETINGS = "CellMeetings",
  DATA = "DATA",
  STATISTICS = "STATISTICS",
  CELLLIST = "CELLLIST",
  MEMBERLIST = "MEMBERLIST",
  CELLHISTORY = "CELLHISTORY",
  HISTORY = "HISTORY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  TERM = "TERM",
  YEAR = "YEAR",
  INFO = "INFO",
  CURRENTTERM = "currentTerm",
  CURRENTTERMYEAR = "currentTermYear",
}

export enum SERVICE_COLLCTION {
  SERVICES = "Services",
  DATA = "DATA",
  TOTALATTENDANCE = "TOTAL_ATTENDANCE",
  SERVICEATTENDANCE = "SERVICE_ATTENDANCE",
  STATISTICS = "STATISTICS",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  TERM = "TERM",
  YEAR = "YEAR",
  MA4WEEK = "MA4WEEK",
}

export enum EVALUATIONFORM_COLLCTION {
  EVALUATIONFORM = "EvaluationForm",
  SETTINGS = "Settings",
  SUBMISSION = "SUBMISSION",
  MEMBERLIST = "MEMBERLIST",
}

export enum NEWMEMBER_COLLECTION {
  NEWMEMBERS = "NewMembers",
  BIRTHYEAR = "BIRTHYEAR_STATS",
  MEMBER = "MEMBER_STATS",
  REGION = "REGION_STATS",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
  GYEONGGI = "GYEONGGI",
  SEOUL = "SEOUL",
  LOCAL = "LOCAL",
}

export enum BARNABAS_COLLCTION {
  BARNABAS = "Barnabas",
  DATA = "DATA",
  STATS = "STATS",
  HISTORY = "HISTORY",
  BARNABAPROFILE = "BarnabaProfile",
  MENTEEPROFILE = "MenteeProfile",
  BARNABAMENTORSHIPS = "BarnabaMentorships",
  AMAZINGMENTORSHIPS = "AmazingMentorships",
  MEETINGSCHEDULES = "MeetingSchedules",
  BARNABASDETAILS = "barnabasDetails",
  ATTENDANCES = "Attendances",
  DATE = "Date",
}
