export enum DALLANTS_COLLCTION {
  DALLENTS = "Dallents",
  ACCOUNTS = "Accounts",
  CELLS = "Cells",
  OTHERS = "Others",
  HISTORY = "History",
  MEMBERS = "Members",
  STATISTIC = "Statistic",
  OVERALL = "Overall",
  CELLSTATISTIC = "CellStatistic",
  SETTINGS = "Settings",
  RESTAURANTS = "Restaurants",
  MENUS = "Menus",
  ORDER = "Order",
  ORDERSTOCK = "OrderStock",
}

export enum CELLMEETING_COLLCTION {
  CELLMEETINGS = "CellMeetings",
  DATA = "DATA",
  STATISTICS = "STATISTICS",
  CELLLIST = "CELLLIST",
  MEMBERLIST = "MEMBERLIST",
  CELLHISTORY = "CELLHISTORY",
  HISTORY = "HISTORY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  TERM = "TERM",
  YEAR = "YEAR",
  INFO = "INFO",
  CURRENTTERM = "currentTerm",
  CURRENTTERMYEAR = "currentTermYear",
}

export enum SERVICE_COLLCTION {
  SERVICES = "Services",
  DATA = "DATA",
  TOTALATTENDANCE = "TOTAL_ATTENDANCE",
  SERVICEATTENDANCE = "SERVICE_ATTENDANCE",
  STATISTICS = "STATISTICS",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  TERM = "TERM",
  YEAR = "YEAR",
}

export enum EVALUATIONFORM_COLLCTION {
  EVALUATIONFORM = "EvaluationForm",
  SETTINGS = "Settings",
  SUBMISSION = "SUBMISSION",
  MEMBERLIST = "MEMBERLIST",
}
