import Head from "next/head";
import {useCallback, useState} from "react";
import {useRecoilState} from "recoil";
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import PageLayout from "../../components/Layout/PageLayout";
import CellMeetingHistory from "../../components/Templates/Cellmeetings/CellMeetingHistory";
import CellMeetingOverview from "../../components/Templates/Cellmeetings/CellMeetingOverview";
import CellMeetingStatistic from "../../components/Templates/Cellmeetings/CellMeetingStatistic";
import {stateSetting} from "../../stores/stateSetting";

const categories = [
  {
    id: 0,
    name: "이번주 셀모임출석(종합)",
    component: <CellMeetingOverview />,
  },
  {
    id: 1,
    name: "과거 셀모임출석 조회",
    component: <CellMeetingHistory />,
  },
  {
    id: 2,
    name: "셀모임출석 통계",
    component: <CellMeetingStatistic />,
  },
];

const CellMeetingPage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);

  const [categoryId, setCategoryId] = useState<number>(
    setting.cellMeetingSelectedCategoryId
  );

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        cellMeetingSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  return (
    <FullScreenLayout>
      <Head>
        <title>셀모임출석 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"셀모임출석현황"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default CellMeetingPage;
