import React from 'react';
import Layout from '../../../../components/Layout/Layout';
import Head from 'next/head';
import PageLayout from '../../../../components/Layout/PageLayout';
import SectionContainer from '../../../../components/Atoms/Container/SectionContainer';
import UserDallant from '../../../../components/Templates/Dallant/UserDallant/UserDallant';

interface DallantPaymentPageProps {}

const DallantPaymentPage = ({}: DallantPaymentPageProps) => {
  
  return (
    <Layout>
      <Head>
        <title>달란트 관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <SectionContainer>
          <UserDallant />
        </SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default DallantPaymentPage
