import React from 'react';
import Layout from '../../../../components/Layout/Layout';
import Head from 'next/head';
import PageLayout from '../../../../components/Layout/PageLayout';
import SectionContainer from '../../../../components/Atoms/Container/SectionContainer';
import { useRouter } from 'next/router';
import Header from '../../../../components/Atoms/Header';

interface DallantPaymentPageProps {}

const DallantPaymentPage = ({}: DallantPaymentPageProps) => {
  const router = useRouter();
  
  return (
    <Layout>
      <Head>
        <title>달란트 관리 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <SectionContainer>
          <Header title={"셀원 디테일"} />
        </SectionContainer>
      </PageLayout>
    </Layout>
  );
};

export default DallantPaymentPage
