import type { NextPage } from "next";
import Head from "next/head";
import Container from "../../components/Atoms/Container/Container";
import Footer from "../../components/Atoms/Footer";
// components
import Layout from "../../components/Layout/Layout";
import MemberSearch from "../../components/Templates/HomeSearch/MemberSearch";

const HomePage: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>청년현황 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="bg-white">
          <MemberSearch />
        </div>
        <Footer />
      </Container>
    </Layout>
  );
};

export default HomePage;
