import Head from 'next/head'
import Layout from '../../components/Layout/Layout'


const Home = () => {

  return (
    <Layout>
      <Head>
        <title>데시보드 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>메인 데시보드</h1>
      </div>
    </Layout>
  )
}

export default Home
