import Head from "next/head";
import Layout from "../../../components/Layout/Layout";
import PageLayout from "../../../components/Layout/PageLayout";

type Props = {};

const BarnabasDetailPage = ({}: Props) => {
  return (
    <Layout>
      <Head>
        <title>바나바명단 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <div>해당 페이지는 개발 예정입니다.</div>
      </PageLayout>
    </Layout>
  );
};

export default BarnabasDetailPage;
