import Head from "next/head";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import FullScreenLayout from "../../../components/Layout/FullScreenLayout";
import PageLayout from "../../../components/Layout/PageLayout";
import BarnabasProfile from "../../../components/Templates/Blessing/BarnabasProfile";

type Props = {};

const BarnabasDetailPage = ({}: Props) => {
  const router = useRouter();
  const [userId, setUserId] = useState<string>("");
  const [userName, setUserName] = useState<string>("");
  const [userCohort, setUserCohort] = useState<string>("0");

  const goBackHandler = () => router.back();

  useEffect(() => {
    if (router.isReady) {
      setUserId(typeof router.query.id === "string" ? router.query.id : "");
      setUserName(
        typeof router.query.name === "string" ? router.query.name : "알수없음"
      );
      setUserCohort(
        typeof router.query.cohort === "string" ? router.query.cohort : "0"
      );
    }
  }, [router]);

  return (
    <FullScreenLayout>
      <Head>
        <title>바나바명단 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <BarnabasProfile
          id={userId}
          name={userName}
          cohort={userCohort}
          goBackHandler={goBackHandler}
        />
      </PageLayout>
    </FullScreenLayout>
  );
};

export default BarnabasDetailPage;
