import React from 'react';
import Layout from '../../components/Layout/Layout';
import Head from 'next/head';
import PageLayout from '../../components/Layout/PageLayout';

type memberProps = {}

const Member = ({}: memberProps) => {
  return (
    <Layout>
      <Head>
        <title>인원현황 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <div className="h-screen flex justify-center items-center">
          <h1 className="text-4xl font-bold">
            현재 페이지는
            <br />
            개발 중입니다
          </h1>
        </div>
      </PageLayout>
    </Layout>
  );
};

export default Member;
