import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
// components
import { AnimatePresence, motion } from "framer-motion";

import AddCellModal from "../../components/Blocks/Modals/AddCellModal";
// graphql
import graphlqlRequestClient from "../../client/graphqlRequestClient";
import {
  FindCellsQuery,
  FindCellsQueryVariables,
  useFindCellsQuery,
} from "../../graphql/generated";
import Layout from "../../components/Layout/Layout";
import useModal from "../../hooks/useModal";
import CellCard from "../../components/Organisms/Cells/CellCard/CellCard";
import Container from "../../components/Atoms/Container/Container";
import Header from "../../components/Atoms/Header";
import SimpleStat from "../../components/Atoms/Stats/SimpleStat";
import Spacer from "../../components/Atoms/Spacer/Spacer";

const Cell: NextPage = () => {
  const { modalOpen, onModalOpenHandler, onModalClosehandleer } = useModal();
  const { isLoading, data } = useFindCellsQuery<
    FindCellsQuery,
    FindCellsQueryVariables
  >(
    graphlqlRequestClient,
    {
      limit: 40,
    },
    {
      staleTime: 60 * 60 * 1000,
      cacheTime: 60 * 60 * 1000 * 24,
    }
  );

  const stats = [
    { name: "연단공동체", number: 15 },
    { name: "인내공동체", number: 12 },
    { name: "능력공동체", number: 9 },
  ];

  return (
    <Layout>
      <Head>
        <title>셀현황 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title={`인터치 셀현황 (${data?.findCells.totalCount || 0}셀)`}>
        <motion.button
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          onClick={onModalOpenHandler}
          className="px-4 py-2 bg-navy-blue text-white rounded-md"
        >
          Add Cell
        </motion.button>
      </Header>
      <Container>
        {isLoading ? (
          <div className="grid grid-cols-2 gap-4 mb-8 lg:grid-cols-3 lg:gap-6 xl:grid-cols-4 3xl:grid-cols-6">
            {Array.from({ length: 6 }, (_, index) => index).map((item) => (
              <div
                key={item}
                className="bg-slate-200 rounded-lg shadow-lg w-30 h-44 lg:h-60 animate-pulse"
              ></div>
            ))}
          </div>
        ) : (
          <>
            <div className="mb-8">
              <SimpleStat stats={stats} row />
            </div>
            <div className="grid grid-cols-2 gap-4 lg:grid-cols-3 lg:gap-6 xl:grid-cols-4 3xl:grid-cols-6">
              {data?.findCells.nodes
                .filter((item) => item.id !== "39")
                .sort((a, b) => {
                  if (a.name > b.name) return 1;
                  else if (b.name > a.name) return -1;
                  else return 0;
                })
                .map((cell) => (
                  <CellCard
                    key={cell.id}
                    id={cell.id}
                    name={cell.name}
                    leader={cell.leaders.at(0)?.name!}
                    totalCountOfMembers={cell.statistics.totalCountOfMembers}
                    countOfActiveMembers={cell.statistics.countOfActiveMembers}
                  />
                ))}
            </div>
            <AnimatePresence
              initial={false}
              exitBeforeEnter={true}
              onExitComplete={() => null}
            >
              {modalOpen && (
                <AddCellModal
                  modalOpen={modalOpen}
                  handleClose={onModalClosehandleer}
                />
              )}
            </AnimatePresence>
          </>
        )}
      </Container>
      <Spacer />
    </Layout>
  );
};

export default Cell;
