import Head from "next/head";
import Image from "next/image";
import Layout from "../../components/Layout/Layout";

const BlessingPage = () => {
  return (
    <Layout>
      <Head>
        <title>블레싱 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex justify-center items-center">
        <h1 className="text-4xl font-bold">
          현재 페이지는
          <br />
          개발 중입니다
        </h1>
      </div>
    </Layout>
  );
};

export default BlessingPage;
