import Head from "next/head";
import {useCallback, useState} from "react";
import {useRecoilState} from "recoil";
import {stateSetting} from "../../stores/stateSetting";
//components
import SectionContainer from "../../components/Atoms/Container/SectionContainer";
import TabsWithHeader from "../../components/Atoms/Tabs/TabsWithHeader";
import FullScreenLayout from "../../components/Layout/FullScreenLayout";
import PageLayout from "../../components/Layout/PageLayout";
import AttendanceOverview from "../../components/Templates/Attendance/AttendanceOverview";
import AttendanceStatistic from "../../components/Templates/Attendance/AttendanceStatistic";
import CellMeetingOverview from "../../components/Templates/Attendance/CellMeetingOverview";
import CellMeetingStatistic from "../../components/Templates/Attendance/CellMeetingStatistic";
import ThisWeekAttendance from "../../components/Templates/Attendance/ThisWeekAttendance";

const categories = [
  {
    id: 0,
    name: "이번주 예배출석(셀별)",
    component: <ThisWeekAttendance />,
  },
  {
    id: 1,
    name: "이번주 예배출석(종합)",
    component: <AttendanceOverview />,
  },
  {
    id: 2,
    name: "이번주 셀모임출석(종합)",
    component: <CellMeetingOverview />,
  },
  {
    id: 3,
    name: "예배출석 통계",
    component: <AttendanceStatistic />,
  },
  {
    id: 4,
    name: "셀모임출석 통계",
    component: <CellMeetingStatistic />,
  },
];

const AttendancePage = () => {
  const [setting, setSetting] = useRecoilState(stateSetting);
  const [categoryId, setCategoryId] = useState<number>(
    setting.blessingSelectedCategoryId
  );

  const setSettingHandler = useCallback(
    (id: number) => {
      setSetting({
        ...setting,
        blessingSelectedCategoryId: id,
      });
    },
    [setting, setSetting]
  );

  return (
    <FullScreenLayout>
      <Head>
        <title>출석현황 | INTOUCH CHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <TabsWithHeader
          title={"출석현황"}
          tabs={categories}
          currentTab={categoryId}
          setCurrentTab={setCategoryId}
          setSettingHandler={setSettingHandler}
        />
        <SectionContainer>{categories[categoryId].component}</SectionContainer>
      </PageLayout>
    </FullScreenLayout>
  );
};

export default AttendancePage;
